version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    gradlew.bat build

    IF NOT EXIST build\libs\penguinmod-1.0.0.jar exit 1
artifacts:
- path: build\libs\penguinmod-1.0.0.jar
  name: main
deploy:
- provider: GitHub
  auth_token:
    secure: G5NAi+1fvUE/+n7j9+Fu3S0z76ZjaO7d9DwcOtiVHYZu7/z7Jhe7wsayXMFGaRUY
  artifact: main
  draft: true
  force_update: true
